"""The metadata type system and the CSV round trip.

Where the risk actually is:

  * **coercion** — the boundary between what a user typed and what the type says
    is representable. Getting this wrong either loses data or stores a value the
    type claims cannot exist,
  * **retyping an existing key**, which has to re-validate everything already
    stored and refuse rather than half-apply,
  * **rename/merge**, the repair for a key that got split by a typo, which walks
    straight into the (image_id, key) unique constraint if done naively,
  * **the CSV importer's dry run** — a preview is only worth approving if it is
    generated by the same code that then does the work.
"""
import pytest
from fastapi import FastAPI
from fastapi.testclient import TestClient
from sqlalchemy import create_engine, event
from sqlalchemy.engine import Engine
from sqlalchemy.orm import sessionmaker

from app.database import database, get_session
import app.database.contours  # noqa: F401
import app.database.dataset_members  # noqa: F401
import app.database.dataset_metadata_keys  # noqa: F401
import app.database.datasets  # noqa: F401
import app.database.image_metadata  # noqa: F401
import app.database.images  # noqa: F401
import app.database.labels  # noqa: F401
import app.database.masks  # noqa: F401
import app.database.rejections  # noqa: F401
import app.database.users  # noqa: F401
from app.database.dataset_members import DatasetMembers
from app.database.datasets import Datasets
from app.database.image_metadata import ImageMetadata
from app.database.images import Images
from app.database.users import Users
from app.exceptions import InvalidMetadataError
from app.routes.general.image_metadata import router as metadata_router
from app.schemas.auth_user import AuthenticatedUser
from app.schemas.permissions import DatasetRole
from app.services import metadata_csv
from app.services.auth import get_current_user
from app.services.database_access import image_metadata as meta
from app.services.metadata_types import MetadataValueType, coerce, infer_type


@event.listens_for(Engine, "connect")
def _fk_pragma(dbapi_connection, connection_record):
    import sqlite3
    if isinstance(dbapi_connection, sqlite3.Connection):
        cur = dbapi_connection.cursor()
        cur.execute("PRAGMA foreign_keys=ON")
        cur.close()


@pytest.fixture
def ctx(tmp_path):
    """A dataset of three plainly-named images and two members."""
    engine = create_engine(f"sqlite:///{tmp_path / 'types.db'}")
    database.metadata.create_all(engine)
    Session = sessionmaker(bind=engine)
    db = Session()

    db.add_all([Users(username="curator", hashed_password="x"),
                Users(username="ann", hashed_password="x")])
    ds = Datasets(name="ds", description="", dataset_type="image",
                  folder_path=str(tmp_path), created_by="curator")
    db.add(ds)
    db.flush()
    db.add_all([
        DatasetMembers(dataset_id=ds.id, username="curator",
                       role=DatasetRole.CURATOR.value,
                       extra_permissions=[], denied_permissions=[]),
        DatasetMembers(dataset_id=ds.id, username="ann",
                       role=DatasetRole.ANNOTATOR.value,
                       extra_permissions=[], denied_permissions=[]),
    ])

    image_ids = []
    for index in range(3):
        image = Images(dataset_id=ds.id, file_name=f"img_{index}.png",
                       file_path=str(tmp_path / f"img_{index}.png"),
                       thumbnail_file_path=str(tmp_path / f"t_{index}.png"),
                       width=10, height=10, color_mode="RGB")
        db.add(image)
        db.flush()
        image_ids.append(image.id)
    db.commit()

    yield {"db": db, "Session": Session, "dataset_id": ds.id, "image_ids": image_ids}
    db.close()
    engine.dispose()


@pytest.fixture
def client(ctx):
    Session = ctx["Session"]
    app = FastAPI()
    app.include_router(metadata_router)
    current = {"username": "curator"}

    def _session_override():
        session = Session()
        try:
            yield session
        finally:
            session.close()

    def _user_override():
        session = Session()
        try:
            row = session.query(Users).filter_by(username=current["username"]).one()
            return AuthenticatedUser.from_query(row)
        finally:
            session.close()

    app.dependency_overrides[get_session] = _session_override
    app.dependency_overrides[get_current_user] = _user_override
    test_client = TestClient(app)

    def as_user(username):
        current["username"] = username
        return test_client

    return as_user


# ---------------------------------------------------------------------------
# Coercion
# ---------------------------------------------------------------------------

def test_number_keeps_its_spelling_and_gains_a_sort_value():
    """"12.0" and "12" are the same number to a filter, but the export should
    read the way it was typed."""
    assert coerce("12.0", MetadataValueType.NUMBER) == ("12.0", 12.0)


def test_a_non_number_is_rejected_rather_than_dropped():
    with pytest.raises(InvalidMetadataError):
        coerce("shallow", MetadataValueType.NUMBER)


def test_non_finite_number_is_rejected():
    for non_finite in ("NaN", "nan", "Inf", "-Inf", "Infinity", "-Infinity"):
        with pytest.raises(InvalidMetadataError, match="not a finite number"):
            coerce(non_finite, MetadataValueType.NUMBER)


def test_dates_canonicalise_to_iso_and_stay_date_only():
    canonical, numeric = coerce("01.05.2024", MetadataValueType.DATE)
    assert canonical == "2024-05-01"
    assert numeric > 0


def test_a_timestamp_keeps_its_precision():
    canonical, _ = coerce("2024-05-01T08:30:00+00:00", MetadataValueType.DATE)
    assert canonical.startswith("2024-05-01T08:30:00")


@pytest.mark.parametrize("written,expected", [
    ("yes", "true"), ("TRUE", "true"), ("1", "true"),
    ("no", "false"), ("f", "false"), ("0", "false"),
])
def test_booleans_canonicalise_however_they_were_written(written, expected):
    canonical, numeric = coerce(written, MetadataValueType.BOOLEAN)
    assert canonical == expected
    assert numeric == (1.0 if expected == "true" else 0.0)


def test_an_open_categorical_key_accepts_anything():
    assert coerce("reef_a", MetadataValueType.CATEGORICAL, []) == ("reef_a", None)


def test_a_locked_categorical_key_refuses_a_new_value():
    """Locking the vocabulary is what stops a typo becoming a fourth subgroup."""
    with pytest.raises(InvalidMetadataError):
        coerce("reef_c", MetadataValueType.CATEGORICAL, ["reef_a", "reef_b"])


# ---------------------------------------------------------------------------
# Inference
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("values,expected", [
    (["1", "0", "1"], MetadataValueType.BOOLEAN),
    (["yes", "no"], MetadataValueType.BOOLEAN),
    (["12", "13.5", "9"], MetadataValueType.NUMBER),
    (["2024-05-01", "2024-06-02"], MetadataValueType.DATE),
    (["reef_a", "reef_b", "reef_a", "reef_b"], MetadataValueType.CATEGORICAL),
])
def test_inference(values, expected):
    assert infer_type(values) == expected


def test_one_unparseable_value_keeps_the_whole_column_categorical():
    """A column of numbers with one "n/a" is not numeric — calling it numeric
    would lose that row on import."""
    assert infer_type(["12", "13", "n/a"]) == MetadataValueType.CATEGORICAL


def test_all_distinct_free_text_is_text_not_a_vocabulary():
    """Nothing repeats, so there are no groups to compare — offering it as a
    grouping would give one image per group."""
    values = [f"a note about specimen {i}" for i in range(10)]
    assert infer_type(values) == MetadataValueType.TEXT


def test_a_tiny_dataset_of_distinct_sites_is_still_a_vocabulary():
    """Three images with three sites must not be called free text just because
    nothing has had a chance to repeat yet."""
    assert infer_type(["reef_a", "reef_b", "reef_c"]) == MetadataValueType.CATEGORICAL


# ---------------------------------------------------------------------------
# Typed writes
# ---------------------------------------------------------------------------

def test_a_new_key_is_categorical_so_nothing_needs_declaring_first(ctx):
    db, image_id = ctx["db"], ctx["image_ids"][0]
    meta.set_metadata_for_images(db, [image_id], {"site": "reef_a"})

    descriptor = meta.get_key(db, ctx["dataset_id"], "site")
    assert descriptor.value_type == MetadataValueType.CATEGORICAL.value


def test_writing_a_declared_numeric_key_fills_the_sort_column(ctx):
    db, image_id = ctx["db"], ctx["image_ids"][0]
    meta.ensure_key(db, ctx["dataset_id"], "depth", MetadataValueType.NUMBER)
    db.commit()
    meta.set_metadata_for_images(db, [image_id], {"depth": "12.5"})

    row = db.query(ImageMetadata).filter_by(image_id=image_id, key="depth").one()
    assert (row.value, row.value_num) == ("12.5", 12.5)


def test_a_value_the_type_rejects_fails_the_whole_batch(ctx):
    """Half a batch tagged is worse than none: the coercion runs before any write."""
    db, image_ids = ctx["db"], ctx["image_ids"]
    meta.ensure_key(db, ctx["dataset_id"], "depth", MetadataValueType.NUMBER)
    db.commit()

    with pytest.raises(InvalidMetadataError):
        meta.set_metadata_for_images(db, image_ids, {"depth": "shallow"})
    assert db.query(ImageMetadata).count() == 0


def test_writing_across_two_datasets_is_refused(ctx, tmp_path):
    """Keys are declared per dataset, so one batch has no single type to check."""
    db = ctx["db"]
    other = Datasets(name="other", description="", dataset_type="image",
                     folder_path=str(tmp_path), created_by="curator")
    db.add(other)
    db.flush()
    outsider = Images(dataset_id=other.id, file_name="x.png", file_path="x",
                      thumbnail_file_path="t", width=1, height=1, color_mode="RGB")
    db.add(outsider)
    db.commit()

    with pytest.raises(InvalidMetadataError):
        meta.set_metadata_for_images(db, [ctx["image_ids"][0], outsider.id],
                                     {"site": "reef_a"})


# ---------------------------------------------------------------------------
# Retyping
# ---------------------------------------------------------------------------

def test_retyping_converts_the_values_already_stored(ctx):
    db, image_ids = ctx["db"], ctx["image_ids"]
    meta.set_metadata_for_images(db, image_ids, {"depth": "12"})

    meta.update_key(db, ctx["dataset_id"], "depth", value_type="number", unit="m")

    rows = db.query(ImageMetadata).filter_by(key="depth").all()
    assert all(row.value_num == 12.0 for row in rows)
    assert meta.get_key(db, ctx["dataset_id"], "depth").unit == "m"


def test_retyping_is_refused_when_a_stored_value_does_not_fit(ctx):
    db, image_ids = ctx["db"], ctx["image_ids"]
    meta.set_metadata_for_images(db, image_ids[:2], {"depth": "12"})
    meta.set_metadata_for_images(db, [image_ids[2]], {"depth": "shallow"})

    with pytest.raises(InvalidMetadataError) as excinfo:
        meta.update_key(db, ctx["dataset_id"], "depth", value_type="number")
    # The message has to name the offender, or there is no way to fix it.
    assert "shallow" in str(excinfo.value)
    assert meta.get_key(db, ctx["dataset_id"], "depth").value_type == "categorical"


def test_narrowing_a_vocabulary_is_refused_when_a_value_falls_outside(ctx):
    db, image_ids = ctx["db"], ctx["image_ids"]
    meta.set_metadata_for_images(db, image_ids[:2], {"site": "reef_a"})
    meta.set_metadata_for_images(db, [image_ids[2]], {"site": "reef_c"})

    with pytest.raises(InvalidMetadataError):
        meta.update_key(db, ctx["dataset_id"], "site", options=["reef_a", "reef_b"])


# ---------------------------------------------------------------------------
# Rename / merge
# ---------------------------------------------------------------------------

def test_rename_moves_every_value(ctx):
    db, image_ids = ctx["db"], ctx["image_ids"]
    meta.set_metadata_for_images(db, image_ids, {"Site": "reef_a"})

    meta.rename_key(db, ctx["dataset_id"], "Site", "site")

    assert meta.get_metadata(db, image_ids[0]) == {"site": "reef_a"}
    assert meta.get_key(db, ctx["dataset_id"], "Site") is None
    assert meta.get_key(db, ctx["dataset_id"], "site") is not None


def test_rename_onto_an_existing_key_is_refused_without_merge(ctx):
    """Folding two vocabularies together silently is not a rename."""
    db, image_ids = ctx["db"], ctx["image_ids"]
    meta.set_metadata_for_images(db, [image_ids[0]], {"Site": "reef_a"})
    meta.set_metadata_for_images(db, [image_ids[1]], {"site": "reef_b"})

    with pytest.raises(InvalidMetadataError):
        meta.rename_key(db, ctx["dataset_id"], "Site", "site")


def test_merge_folds_the_split_key_back_together(ctx):
    db, image_ids = ctx["db"], ctx["image_ids"]
    meta.set_metadata_for_images(db, [image_ids[0]], {"Site": "reef_a"})
    meta.set_metadata_for_images(db, [image_ids[1]], {"site": "reef_b"})

    result = meta.rename_key(db, ctx["dataset_id"], "Site", "site", merge=True)

    assert result["renamed"] == 1
    assert meta.get_metadata(db, image_ids[0]) == {"site": "reef_a"}
    assert meta.get_metadata(db, image_ids[1]) == {"site": "reef_b"}
    assert [facet["key"] for facet in meta.get_dataset_facets(db, ctx["dataset_id"])] == ["site"]


def test_merge_on_an_image_carrying_both_keeps_the_renamed_one(ctx):
    """The caller named the source as the key to keep, so it wins the collision —
    and the old target row must be deleted before the rename to avoid tripping
    the (image_id, key) unique constraint."""
    db, image_id = ctx["db"], ctx["image_ids"][0]
    meta.set_metadata_for_images(db, [image_id], {"Site": "reef_a", "site": "reef_b"})

    result = meta.rename_key(db, ctx["dataset_id"], "Site", "site", merge=True)

    assert result["merged"] == 1
    assert meta.get_metadata(db, image_id) == {"site": "reef_a"}


def test_deleting_a_key_removes_its_values_and_its_declaration(ctx):
    db, image_ids = ctx["db"], ctx["image_ids"]
    meta.set_metadata_for_images(db, image_ids, {"site": "reef_a"})

    assert meta.delete_key_from_dataset(db, ctx["dataset_id"], "site") == 3
    assert meta.get_key(db, ctx["dataset_id"], "site") is None
    assert meta.get_metadata(db, image_ids[0]) == {}


# ---------------------------------------------------------------------------
# Typed filtering
# ---------------------------------------------------------------------------

def test_numeric_range_filter(ctx):
    db, image_ids = ctx["db"], ctx["image_ids"]
    meta.ensure_key(db, ctx["dataset_id"], "depth", MetadataValueType.NUMBER)
    db.commit()
    for image_id, depth in zip(image_ids, ["2", "12", "30"]):
        meta.set_metadata_for_images(db, [image_id], {"depth": depth})

    matched = meta.filter_image_ids(db, ctx["dataset_id"], {"depth": {"min": 5, "max": 20}})
    assert matched == [image_ids[1]]


def test_an_open_ended_range_filters_on_one_side_only(ctx):
    db, image_ids = ctx["db"], ctx["image_ids"]
    meta.ensure_key(db, ctx["dataset_id"], "depth", MetadataValueType.NUMBER)
    db.commit()
    for image_id, depth in zip(image_ids, ["2", "12", "30"]):
        meta.set_metadata_for_images(db, [image_id], {"depth": depth})

    assert set(meta.filter_image_ids(db, ctx["dataset_id"], {"depth": {"min": 10}})) == {
        image_ids[1], image_ids[2]
    }


def test_date_range_filters_chronologically(ctx):
    db, image_ids = ctx["db"], ctx["image_ids"]
    meta.ensure_key(db, ctx["dataset_id"], "collected", MetadataValueType.DATE)
    db.commit()
    for image_id, day in zip(image_ids, ["2024-01-05", "2024-06-01", "2024-11-20"]):
        meta.set_metadata_for_images(db, [image_id], {"collected": day})

    from app.services.metadata_types import coerce as _coerce
    low = _coerce("2024-05-01", MetadataValueType.DATE)[1]
    high = _coerce("2024-07-01", MetadataValueType.DATE)[1]
    assert meta.filter_image_ids(
        db, ctx["dataset_id"], {"collected": {"min": low, "max": high}}
    ) == [image_ids[1]]


def test_text_contains_filter(ctx):
    db, image_ids = ctx["db"], ctx["image_ids"]
    meta.ensure_key(db, ctx["dataset_id"], "notes", MetadataValueType.TEXT)
    db.commit()
    meta.set_metadata_for_images(db, [image_ids[0]], {"notes": "bleached colony"})
    meta.set_metadata_for_images(db, [image_ids[1]], {"notes": "healthy"})

    assert meta.filter_image_ids(
        db, ctx["dataset_id"], {"notes": {"contains": "bleach"}}
    ) == [image_ids[0]]


def test_facets_report_the_range_of_an_ordered_key(ctx):
    db, image_ids = ctx["db"], ctx["image_ids"]
    meta.ensure_key(db, ctx["dataset_id"], "depth", MetadataValueType.NUMBER)
    db.commit()
    for image_id, depth in zip(image_ids, ["2", "12", "30"]):
        meta.set_metadata_for_images(db, [image_id], {"depth": depth})

    facet = meta.get_dataset_facets(db, ctx["dataset_id"])[0]
    assert facet["range"] == {"min": 2.0, "max": 30.0}
    assert facet["groupable"] is False, "a near-unique number is not a subgroup"
    # Ordered keys are listed in value order, not by popularity: 2, 12, 30 is a
    # scale; sorted by count it would be noise.
    assert [entry["value"] for entry in facet["values"]] == ["2", "12", "30"]


def test_a_declared_but_unused_key_still_appears(ctx):
    db = ctx["db"]
    meta.ensure_key(db, ctx["dataset_id"], "treatment", MetadataValueType.CATEGORICAL)
    db.commit()

    facets = meta.get_dataset_facets(db, ctx["dataset_id"])
    assert [facet["key"] for facet in facets] == ["treatment"]
    assert facets[0]["values"] == []


# ---------------------------------------------------------------------------
# CSV round trip
# ---------------------------------------------------------------------------

def test_export_of_an_untagged_dataset_is_the_template(ctx):
    """Starting from the export is what makes the filenames match on the way in."""
    csv_text = metadata_csv.export_csv(ctx["db"], ctx["dataset_id"])
    lines = csv_text.strip().splitlines()
    assert lines[0] == "file_name"
    assert lines[1:] == ["img_0.png", "img_1.png", "img_2.png"]


def test_export_then_import_is_a_round_trip(ctx):
    db, image_ids = ctx["db"], ctx["image_ids"]
    meta.set_metadata_for_images(db, image_ids[:2], {"site": "reef_a"})

    exported = metadata_csv.export_csv(db, ctx["dataset_id"])
    meta.delete_key_from_dataset(db, ctx["dataset_id"], "site")
    assert meta.get_metadata(db, image_ids[0]) == {}

    metadata_csv.import_csv(db, ctx["dataset_id"], exported.encode(), dry_run=False)
    assert meta.get_metadata(db, image_ids[0]) == {"site": "reef_a"}
    assert meta.get_metadata(db, image_ids[2]) == {}


def _csv(*lines: str) -> bytes:
    return "\n".join(lines).encode()


def test_dry_run_reports_without_writing(ctx):
    db = ctx["db"]
    content = _csv("file_name,site", "img_0.png,reef_a", "img_1.png,reef_b")

    result = metadata_csv.import_csv(db, ctx["dataset_id"], content, dry_run=True)

    assert result["matched"] == 2
    assert result["missing_from_file"] == ["img_2.png"]
    assert result["written"] == 0
    assert db.query(ImageMetadata).count() == 0


def test_unmatched_filenames_are_reported_not_guessed(ctx):
    db = ctx["db"]
    content = _csv("file_name,site", "img_0.png,reef_a", "nope.png,reef_b")

    result = metadata_csv.import_csv(db, ctx["dataset_id"], content, dry_run=True)

    assert result["matched"] == 1
    assert result["unmatched"] == ["nope.png"]


def test_import_infers_a_type_for_each_new_column(ctx):
    db = ctx["db"]
    content = _csv("file_name,depth,collected,site",
                   "img_0.png,12,2024-05-01,reef_a",
                   "img_1.png,30,2024-06-02,reef_b")

    result = metadata_csv.import_csv(db, ctx["dataset_id"], content, dry_run=True)

    by_key = {column["key"]: column for column in result["columns"]}
    assert by_key["depth"]["value_type"] == "number"
    assert by_key["collected"]["value_type"] == "date"
    assert by_key["site"]["value_type"] == "categorical"
    assert all(column["is_new"] for column in result["columns"])


def test_applying_the_import_declares_the_inferred_types(ctx):
    db = ctx["db"]
    content = _csv("file_name,depth", "img_0.png,12", "img_1.png,30")

    metadata_csv.import_csv(db, ctx["dataset_id"], content, dry_run=False)

    assert meta.get_key(db, ctx["dataset_id"], "depth").value_type == "number"
    row = db.query(ImageMetadata).filter_by(key="depth").first()
    assert row.value_num == 12.0


def test_a_value_rejected_by_an_existing_key_blocks_the_import(ctx):
    db, image_ids = ctx["db"], ctx["image_ids"]
    meta.ensure_key(db, ctx["dataset_id"], "depth", MetadataValueType.NUMBER)
    db.commit()
    content = _csv("file_name,depth", "img_0.png,12", "img_1.png,shallow")

    result = metadata_csv.import_csv(db, ctx["dataset_id"], content, dry_run=False)

    assert result["errors"], "the offending value must be reported"
    assert result["written"] == 0
    assert db.query(ImageMetadata).count() == 0


def test_import_is_additive_unless_replace_is_asked_for(ctx):
    db, image_ids = ctx["db"], ctx["image_ids"]
    meta.set_metadata_for_images(db, [image_ids[0]], {"notes": "keep me"})
    content = _csv("file_name,site", "img_0.png,reef_a")

    metadata_csv.import_csv(db, ctx["dataset_id"], content, dry_run=False)
    assert meta.get_metadata(db, image_ids[0]) == {"notes": "keep me", "site": "reef_a"}

    metadata_csv.import_csv(db, ctx["dataset_id"], content, dry_run=False, replace=True)
    assert meta.get_metadata(db, image_ids[0]) == {"site": "reef_a"}


def test_semicolon_and_bom_files_from_excel_still_match(ctx):
    """Excel writes a BOM and, in much of Europe, semicolons. Without handling
    both, a correct-looking file matches nothing."""
    db, image_ids = ctx["db"], ctx["image_ids"]
    content = "﻿" + "\n".join(["file_name;site", "img_0.png;reef_a"])

    result = metadata_csv.import_csv(db, ctx["dataset_id"], content.encode(),
                                     dry_run=False)

    assert result["matched"] == 1
    assert meta.get_metadata(db, image_ids[0]) == {"site": "reef_a"}


def test_matching_by_image_id_is_supported(ctx):
    db, image_ids = ctx["db"], ctx["image_ids"]
    content = _csv("image_id,site", f"{image_ids[0]},reef_a")

    metadata_csv.import_csv(db, ctx["dataset_id"], content, dry_run=False)
    assert meta.get_metadata(db, image_ids[0]) == {"site": "reef_a"}


def test_a_file_without_an_image_column_is_refused(ctx):
    with pytest.raises(InvalidMetadataError):
        metadata_csv.import_csv(ctx["db"], ctx["dataset_id"],
                                _csv("site,depth", "reef_a,12"))


def test_matching_does_not_reach_into_another_dataset(ctx, tmp_path):
    db = ctx["db"]
    other = Datasets(name="other", description="", dataset_type="image",
                     folder_path=str(tmp_path), created_by="curator")
    db.add(other)
    db.flush()
    db.add(Images(dataset_id=other.id, file_name="theirs.png", file_path="x",
                  thumbnail_file_path="t", width=1, height=1, color_mode="RGB"))
    db.commit()

    result = metadata_csv.import_csv(db, ctx["dataset_id"],
                                     _csv("file_name,site", "theirs.png,reef_a"),
                                     dry_run=True)
    assert result["matched"] == 0
    assert result["unmatched"] == ["theirs.png"]


# ---------------------------------------------------------------------------
# Over HTTP
# ---------------------------------------------------------------------------

def test_csv_download_and_upload_over_http(ctx, client):
    response = client("curator").get(f"/metadata/dataset/{ctx['dataset_id']}/csv")
    assert response.status_code == 200
    assert response.text.strip().splitlines()[0] == "file_name"

    upload = client("curator").post(
        f"/metadata/dataset/{ctx['dataset_id']}/import",
        params={"dry_run": False},
        files={"file": ("meta.csv", b"file_name,site\nimg_0.png,reef_a\n", "text/csv")},
    )
    assert upload.status_code == 200
    assert upload.json()["written"] == 1


def test_import_needs_the_write_permission(ctx, client):
    response = client("ann").post(
        f"/metadata/dataset/{ctx['dataset_id']}/import",
        files={"file": ("meta.csv", b"file_name,site\nimg_0.png,reef_a\n", "text/csv")},
    )
    assert response.status_code == 403


def test_key_declaration_over_http(ctx, client):
    dataset_id = ctx["dataset_id"]
    client("curator").post("/metadata/images",
                           json={"image_ids": ctx["image_ids"], "entries": {"depth": "12"}})

    response = client("curator").put(
        f"/metadata/dataset/{dataset_id}/keys/depth",
        json={"value_type": "number", "unit": "m"},
    )
    assert response.status_code == 200
    assert response.json()["key"] == {
        "key": "depth", "value_type": "number", "unit": "m",
        "options": [], "description": None,
    }

    listed = client("ann").get(f"/metadata/dataset/{dataset_id}/keys").json()["keys"]
    assert listed[0]["value_type"] == "number"


def test_retyping_over_http_is_a_422_naming_the_offender(ctx, client):
    dataset_id = ctx["dataset_id"]
    client("curator").post("/metadata/images",
                           json={"image_ids": [ctx["image_ids"][0]],
                                 "entries": {"depth": "shallow"}})

    response = client("curator").put(
        f"/metadata/dataset/{dataset_id}/keys/depth", json={"value_type": "number"}
    )
    assert response.status_code == 422
    assert "shallow" in response.json()["detail"]


def test_rename_over_http(ctx, client):
    dataset_id = ctx["dataset_id"]
    client("curator").post("/metadata/images",
                           json={"image_ids": ctx["image_ids"], "entries": {"Site": "reef_a"}})

    response = client("curator").post(
        f"/metadata/dataset/{dataset_id}/keys/Site/rename",
        json={"new_key": "site"},
    )
    assert response.status_code == 200
    assert response.json()["renamed"] == 3


def test_type_catalog_says_what_can_be_grouped(ctx, client):
    types = {entry["value_type"]: entry
             for entry in client("ann").get("/metadata/types").json()["types"]}
    assert types["categorical"]["groupable"] is True
    assert types["number"]["groupable"] is False
    assert types["number"]["ordered"] is True
